import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";

type PageProps = { params: Promise<{ lang: string }> };

const sections = [
  ["01", "Pass og innreisekrav", "Passport and entry requirements", ["Kontroller at passet er gyldig og uskadd", "Sjekk landets krav til gyldighetstid, visum og innreiseskjema", "Kontroller reglene også ved mellomlanding", "Lagre kopi av viktige dokumenter separat"], ["Check that your passport is valid and undamaged", "Review the country's validity, visa and entry-form requirements", "Check the rules for transit stops as well", "Store a copy of important documents separately"]],
  ["02", "Helse og forsikring", "Health and insurance", ["Kontroller hva reiseforsikringen dekker", "Ta med nødvendige medisiner i original emballasje", "Undersøk vaksiner og helseråd i god tid", "Lagre nummeret til forsikringens alarmsentral"], ["Review what your travel insurance covers", "Bring necessary medication in its original packaging", "Check vaccination and health advice well in advance", "Save the insurer's emergency assistance number"]],
  ["03", "Betaling og budsjett", "Payments and budget", ["Ta med minst to betalingsmuligheter", "Kontroller kortgrenser og eventuell regionsperre", "Se etter valutapåslag og uttaksgebyrer", "Ha en liten økonomisk reserve til uforutsette utgifter"], ["Bring at least two ways to pay", "Check card limits and any regional restrictions", "Review foreign-exchange markups and withdrawal fees", "Keep a small financial reserve for unexpected costs"]],
  ["04", "Mobil og digitale kopier", "Mobile access and digital copies", ["Kontroller roaming eller eSIM før avreise", "Last ned billetter, kart og adresser for bruk uten nett", "Aktiver skjermlås og sikkerhetskopi", "Oppbevar nødnumre og bookingreferanser lett tilgjengelig"], ["Check roaming or eSIM before departure", "Download tickets, maps and addresses for offline use", "Enable a screen lock and backup", "Keep emergency numbers and booking references accessible"]],
  ["05", "Transport og ankomst", "Transport and arrival", ["Kontroller flytid, terminal og bagasjeregler", "Planlegg transport fra flyplassen", "Lagre adressen til overnattingsstedet", "Legg inn litt tidsmargin ved bytter og avtaler"], ["Confirm flight time, terminal and baggage rules", "Plan transport from the airport", "Save the accommodation address", "Allow extra time for connections and appointments"]],
  ["06", "Det praktiske hjemme", "Practical tasks at home", ["Ordne planter, post og eventuelle kjæledyr", "Lukk vinduer og slå av det som ikke må stå på", "Ikke del unødvendig mye om et tomt hjem offentlig", "Gi en betrodd person reiseplan og kontaktinformasjon"], ["Arrange care for plants, mail and any pets", "Close windows and switch off anything not needed", "Avoid publicly sharing unnecessary details about an empty home", "Give a trusted person your itinerary and contact details"]],
];

const faq = [
  ["Hvor tidlig bør jeg begynne med sjekklisten?", "How early should I start the checklist?", "Kontroller pass, visum, vaksiner og forsikring så snart reisen planlegges. Billetter, mobil, betaling og pakking kan deretter ferdigstilles nærmere avreise.", "Check passport, visa, vaccinations and insurance as soon as the trip is planned. Tickets, mobile access, payments and packing can then be finalised closer to departure."],
  ["Hvor finner jeg riktige innreiseregler?", "Where can I find the correct entry rules?", "Bruk offisielle myndighetskilder for reisemålet og kontroller informasjonen på nytt før avreise. Krav kan endres, og ulike regler kan gjelde for nasjonalitet, reiserute og oppholdslengde.", "Use official government sources for the destination and check again before departure. Requirements can change and may depend on nationality, itinerary and length of stay."],
  ["Bør dokumentene bare ligge på mobilen?", "Should documents only be stored on my phone?", "Nei. Ha gjerne dokumentene tilgjengelig uten nett, men oppbevar også en separat kopi eller sikker skyløsning i tilfelle mobilen blir borte eller tom for strøm.", "No. Make documents available offline, but also keep a separate copy or secure cloud backup in case the phone is lost or runs out of power."],
];

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { lang } = await params;
  const no = lang === "no";
  return {
    title: no ? "Sjekkliste før utenlandsreisen | Flyferie.no" : "Checklist before international travel | Flyferie.no",
    description: no ? "Praktisk sjekkliste før utenlandsreisen: pass, innreisekrav, helse, forsikring, betaling, mobil, transport og hjemmet." : "A practical pre-travel checklist covering passport, entry rules, health, insurance, payments, mobile access, transport and home.",
    alternates: { canonical: `/${lang}/guides/international-travel-checklist`, languages: { "nb-NO": "/no/guides/international-travel-checklist", en: "/en/guides/international-travel-checklist", "x-default": "/no/guides/international-travel-checklist" } },
  };
}

export default async function InternationalTravelChecklistPage({ params }: PageProps) {
  const { lang } = await params;
  if (lang !== "no" && lang !== "en") notFound();
  const no = lang === "no";
  const other = no ? "en" : "no";
  const pageUrl = `https://flyferie.no/${lang}/guides/international-travel-checklist`;
  const jsonLd = { "@context": "https://schema.org", "@graph": [
    { "@type": "Article", headline: no ? "Sjekkliste før utenlandsreisen" : "Checklist before international travel", description: no ? "En praktisk sjekkliste for de viktigste forberedelsene før en utenlandsreise." : "A practical checklist for key preparations before international travel.", inLanguage: no ? "nb-NO" : "en", url: pageUrl, publisher: { "@id": "https://flyferie.no/#organization" } },
    { "@type": "FAQPage", mainEntity: faq.map((item) => ({ "@type": "Question", name: no ? item[0] : item[1], acceptedAnswer: { "@type": "Answer", text: no ? item[2] : item[3] } })) },
    { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: no ? "Forside" : "Home", item: `https://flyferie.no/${lang}` }, { "@type": "ListItem", position: 2, name: no ? "Guider" : "Guides", item: `https://flyferie.no/${lang}/guides` }, { "@type": "ListItem", position: 3, name: no ? "Sjekkliste før utenlandsreisen" : "International travel checklist", item: pageUrl }] },
  ] };

  return <main className="min-h-screen bg-[#fffaf1] text-[#17332f]">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} />
    <header className="bg-[#102f2b] text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><Link href={`/${lang}`}><Image src="/flyferie-logo-v9.png" alt="Flyferie.no" width={480} height={200} priority className="h-auto w-[185px] sm:w-[225px]" /></Link><div className="flex items-center gap-4"><Link href={`/${lang}/guides`} className="text-sm font-bold">{no ? "Guider" : "Guides"}</Link><Link href={`/${other}/guides/international-travel-checklist`} className="rounded-full border border-white/40 px-4 py-2 text-sm font-bold">{no ? "EN" : "NO"}</Link></div></div></header>
    <section className="relative overflow-hidden bg-[#173f39] px-5 py-16 text-white sm:py-24 lg:px-8"><div className="absolute -right-24 -top-28 h-80 w-80 rounded-full bg-[#f4b860]/25 blur-3xl" /><div className="relative mx-auto max-w-6xl"><Link href={`/${lang}/guides`} className="text-sm font-bold text-[#ffd078]">← {no ? "Tilbake til guidene" : "Back to the guides"}</Link><p className="mt-9 text-xs font-bold uppercase tracking-[.22em] text-[#ffd078]">{no ? "Dokumenter · trygghet · praktiske detaljer" : "Documents · safety · practical details"}</p><h1 className="display mt-3 max-w-5xl text-[48px] font-bold leading-[.98] sm:text-7xl lg:text-[82px]">{no ? "Sjekkliste før utenlandsreisen" : "Checklist before international travel"}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/80 sm:text-xl">{no ? "De viktigste forberedelsene begynner før kofferten pakkes. Gå gjennom denne listen i god tid, og kontroller alltid oppdaterte krav hos offisielle kilder." : "The most important preparations begin before packing. Work through this list in good time and always verify current requirements with official sources."}</p></div></section>
    <section className="px-5 py-12 sm:py-16 lg:px-8"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#e16f59]">{no ? "Før avreise" : "Before departure"}</p><h2 className="display mt-3 text-[38px] font-bold sm:text-5xl">{no ? "Seks områder å gå gjennom" : "Six areas to review"}</h2><div className="mt-8 grid gap-5 lg:grid-cols-2">{sections.map((item) => { const items = no ? item[3] : item[4]; return <article key={item[0] as string} className="rounded-[26px] border border-[#17332f]/10 bg-white p-6 shadow-sm sm:p-8"><div className="flex items-start gap-4"><span className="rounded-full bg-[#f4d7a1] px-3 py-1.5 text-xs font-bold text-[#b94f3d]">{item[0] as string}</span><h3 className="display text-3xl font-bold leading-tight">{(no ? item[1] : item[2]) as string}</h3></div><ul className="mt-6 space-y-3">{(items as string[]).map((point) => <li key={point} className="flex gap-3 leading-7 text-[#48645f]"><span className="font-bold text-[#e16f59]">✓</span><span>{point}</span></li>)}</ul></article>; })}</div></div></section>
    <section className="bg-[#edf4ef] px-5 py-12 lg:px-8 lg:py-16"><div className="mx-auto grid max-w-6xl gap-7 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#1e776e]">{no ? "Flyferies råd" : "Flyferie's advice"}</p><h2 className="display mt-3 text-[38px] font-bold leading-tight sm:text-5xl">{no ? "Gjør det viktigste først" : "Handle on the essentials first"}</h2></div><div className="rounded-[24px] bg-white p-7 shadow-sm sm:p-9"><p className="text-lg leading-8 text-[#365b55]">{no ? "Pass, innreisekrav, nødvendige medisiner og forsikring kan kreve tid å ordne. Start der. Bruk deretter de siste dagene før avreise til billetter, betaling, mobil, bagasje og hjemmet." : "Passport, entry requirements, essential medication and insurance can take time to arrange. Start there. Use the final days before departure for tickets, payments, mobile access, baggage and home preparations."}</p></div></div></section>
    <section className="px-5 py-12 sm:py-16 lg:px-8"><div className="mx-auto max-w-4xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#e16f59]">{no ? "Vanlige spørsmål" : "Frequently asked questions"}</p><div className="mt-7 space-y-4">{faq.map((item) => <article key={item[1]} className="rounded-[22px] border border-[#17332f]/10 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">{no ? item[0] : item[1]}</h2><p className="mt-3 leading-7 text-[#48645f]">{no ? item[2] : item[3]}</p></article>)}</div><div className="mt-8 flex flex-wrap gap-3"><Link href={`/${lang}/guides/travel-insurance`} className="inline-flex rounded-full bg-[#17332f] px-6 py-3.5 font-bold text-white">{no ? "Kontroller reiseforsikringen" : "Check your travel insurance"} →</Link><Link href={`/${lang}/guides/esim`} className="inline-flex rounded-full border border-[#17332f]/25 bg-white px-6 py-3.5 font-bold">{no ? "Guide til eSIM" : "Guide to eSIM"} →</Link><Link href={`/${lang}/guides/weekend-packing-list`} className="inline-flex rounded-full border border-[#17332f]/25 bg-white px-6 py-3.5 font-bold">{no ? "Pakkeliste for weekendtur" : "Weekend packing list"} →</Link></div></div></section>
    <footer className="bg-[#102f2b] px-5 py-10 text-white/65"><div className="mx-auto flex max-w-7xl flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><Image src="/flyferie-logo-v9.png" alt="Flyferie.no" width={480} height={200} className="h-auto w-[210px]" /><p className="text-sm">© 2026 Flyferie.no · {no ? "Reiseinspirasjon for nye opplevelser" : "Travel inspiration for new experiences"}</p></div></footer>
  </main>;
}
