import { destinationGuides as existingGuides, type DestinationGuide } from "@/lib/content";

type Pair = [no: string, en: string];
type Weekend = [timeNo: string, timeEn: string, titleNo: string, titleEn: string, textNo: string, textEn: string];
type District = [name: string, textNo: string, textEn: string];
type Tip = [titleNo: string, titleEn: string, textNo: string, textEn: string];

export type CompleteDestinationGuide = DestinationGuide & {
  transportUrl: string;
  transportName: string;
};

function makeGuide(config: {
  seo: Pair;
  intro: Pair;
  bestFor: Pair[];
  stay: Pair;
  areas: Pair;
  transport: Pair;
  airport: Pair;
  weekend: Weekend[];
  districts: District[];
  tips: Tip[];
  transportUrl: string;
  transportName: string;
}): CompleteDestinationGuide {
  return {
    seoNo: config.seo[0], seoEn: config.seo[1],
    introNo: config.intro[0], introEn: config.intro[1],
    bestFor: config.bestFor.map(([no, en]) => ({ no, en })),
    facts: [
      { labelNo: "Anbefalt lengde", labelEn: "Recommended stay", valueNo: config.stay[0], valueEn: config.stay[1] },
      { labelNo: "Beste områder", labelEn: "Best areas", valueNo: config.areas[0], valueEn: config.areas[1] },
      { labelNo: "Transport", labelEn: "Transport", valueNo: config.transport[0], valueEn: config.transport[1] },
      { labelNo: "Flyplass", labelEn: "Airport", valueNo: config.airport[0], valueEn: config.airport[1] }
    ],
    weekend: config.weekend.map(([timeNo, timeEn, titleNo, titleEn, textNo, textEn]) => ({ timeNo, timeEn, titleNo, titleEn, textNo, textEn })),
    districts: config.districts.map(([name, textNo, textEn]) => ({ name, textNo, textEn })),
    tips: config.tips.map(([titleNo, titleEn, textNo, textEn]) => ({ titleNo, titleEn, textNo, textEn })),
    transportUrl: config.transportUrl,
    transportName: config.transportName
  };
}

const guides: Record<string, CompleteDestinationGuide> = {
  berlin: {
    ...existingGuides.berlin,
    transportUrl: "https://www.bvg.de/en/tourists/transportation-tariff-zones",
    transportName: "BVG"
  },
  tbilisi: makeGuide({
    seo: ["Tbilisi-guide: overraskende storbyweekend", "Tbilisi guide: a surprising city break"],
    intro: ["Tbilisi blander gamle balkonghus, svovelbad, vinbarer og moderne kreativitet i en by som fortsatt føles som et funn. Prisnivået er hyggelig, avstandene overkommelige og utsikten dramatisk.", "Tbilisi blends old balcony houses, sulphur baths, wine bars and modern creativity in a city that still feels like a discovery. Prices are friendly, distances manageable and the views dramatic."],
    bestFor: [["Skjulte perler", "Hidden gems"], ["Mat og vin", "Food and wine"], ["Vennegjenger", "Groups of friends"], ["Kultur og historie", "Culture and history"]],
    stay: ["3 netter", "3 nights"], areas: ["Gamle Tbilisi, Sololaki og Vera", "Old Tbilisi, Sololaki and Vera"], transport: ["Metro, buss og taxi", "Metro, bus and taxi"], airport: ["Tbilisi internasjonale lufthavn", "Tbilisi International Airport"],
    weekend: [
      ["Fredag kveld", "Friday evening", "Gamlebyen og georgisk middag", "Old Town and a Georgian dinner", "Start ved Meidan, gå mellom balkonghusene og bestill flere småretter til deling. Avslutt med lokal vin i Sololaki.", "Begin at Meidan, wander between the balcony houses and order several dishes to share. Finish with Georgian wine in Sololaki."],
      ["Lørdag", "Saturday", "Festning, bad og nye nabolag", "Fortress, baths and new neighbourhoods", "Ta taubanen mot Narikala, gå ned gjennom Abanotubani og prøv et svovelbad. Senere passer Fabrika og området rundt for mat, design og barer.", "Take the cable car towards Narikala, walk down through Abanotubani and try a sulphur bath. Later, Fabrika and its surroundings are good for food, design and bars."],
      ["Søndag", "Sunday", "Marked og rolig utsikt", "Market and a slower view", "Se etter kunst og antikviteter ved Dry Bridge, spis en lang lunsj og avslutt med utsikt fra Mtatsminda før flyreisen hjem.", "Browse art and antiques at Dry Bridge, enjoy a long lunch and finish with views from Mtatsminda before flying home."]
    ],
    districts: [["Gamle Tbilisi", "Best for den klassiske utsikten, badene og første besøk.", "Best for classic views, baths and a first visit."], ["Sololaki", "Vakre bygårder, små restauranter og vinbarer.", "Historic townhouses, small restaurants and wine bars."], ["Vera", "Avslappet, kreativt og godt plassert mellom sentrum og åsene.", "Relaxed, creative and well placed between the centre and hills."], ["Marjanishvili", "Fabrika, lokal stemning og enkel tilgang til metro.", "Fabrika, local atmosphere and easy metro access."]],
    tips: [["Bestill svovelbad", "Book a sulphur bath", "Private rom blir ofte fulle i helgene, så bestill på forhånd.", "Private rooms often fill at weekends, so book ahead."], ["Bruk etablerte taxiapper", "Use established taxi apps", "Avtal pris i appen fremfor å forhandle på gaten.", "Set the fare in an app instead of negotiating on the street."], ["Ikke undervurder bakkene", "Do not underestimate the hills", "Gode sko gjør gamlebyen og utsiktspunktene langt hyggeligere.", "Good shoes make the Old Town and viewpoints much easier." ]],
    transportUrl: "https://ttc.com.ge/en", transportName: "Tbilisi Transport Company"
  }),
  krakow: makeGuide({
    seo: ["Krakow-guide: historie, mat og god verdi", "Krakow guide: history, food and great value"],
    intro: ["Krakow er kompakt nok for en enkel helg, men rik nok til at dagene fylles raskt. Gamlebyen, Kazimierz, gode restauranter og sterke historiske opplevelser ligger tett.", "Krakow is compact enough for an easy weekend yet rich enough to fill every day. The Old Town, Kazimierz, strong restaurants and powerful historic experiences sit close together."],
    bestFor: [["Førstegangsbesøk", "First-time visitors"], ["Historie", "History"], ["Mat og barer", "Food and bars"], ["God verdi", "Great value"]],
    stay: ["2–3 netter", "2–3 nights"], areas: ["Stare Miasto, Kazimierz og Podgórze", "Stare Miasto, Kazimierz and Podgórze"], transport: ["Trikk, buss og gange", "Tram, bus and walking"], airport: ["Krakow lufthavn", "Krakow Airport"],
    weekend: [["Fredag kveld", "Friday evening", "Markedsplassen etter mørkets frembrudd", "The Market Square after dark", "Gå gjennom Stare Miasto, se Mariakirken og finn middag i sidegatene rundt Rynek Główny.", "Walk through the Old Town, see St Mary's Basilica and find dinner in the streets around the Main Square."], ["Lørdag", "Saturday", "Wawel og Kazimierz", "Wawel and Kazimierz", "Start ved Wawel-høyden, følg elven og bruk ettermiddagen i Kazimierz. Om kvelden ligger barene og restaurantene tett.", "Start at Wawel Hill, follow the river and spend the afternoon in Kazimierz. In the evening, bars and restaurants are close together."], ["Søndag", "Sunday", "Podgórze eller en historisk utflukt", "Podgórze or a historic excursion", "Utforsk Podgórze og museene der, eller reserver en større utflukt på forhånd. Ikke press for mye inn før hjemreisen.", "Explore Podgórze and its museums, or reserve a major excursion in advance. Avoid squeezing too much in before your flight."]],
    districts: [["Stare Miasto", "Nær de største severdighetene og best for et kort førstegangsbesøk.", "Close to the major sights and best for a short first visit."], ["Kazimierz", "Restauranter, historie, småbutikker og kveldsstemning.", "Restaurants, history, independent shops and evening atmosphere."], ["Podgórze", "Roligere base med viktige historiske steder sør for elven.", "A quieter base with important historic sites south of the river."], ["Kleparz", "Lokalt marked og kort vei til gamlebyen og stasjonen.", "A local market and a short walk to the Old Town and station."]],
    tips: [["Bestill populære museer", "Book popular museums", "Tidsluker kan bli utsolgt, særlig i helger og høysesong.", "Timed entries can sell out, especially at weekends and in high season."], ["Bruk trikken utenfor sentrum", "Use trams beyond the centre", "Gamlebyen oppleves best til fots, mens trikken er effektiv videre ut.", "The Old Town is best on foot, while trams work well farther out."], ["Sett av tid til måltidene", "Leave time for meals", "Krakow har mer enn pierogi; prøv både melkebarer og nyere polske kjøkken.", "Krakow offers more than pierogi; try both milk bars and modern Polish cooking."]],
    transportUrl: "https://ztp.krakow.pl/en", transportName: "ZTP Krakow"
  }),
  madrid: makeGuide({
    seo: ["Madrid-guide: mat, fotball og storbyliv", "Madrid guide: food, football and city life"],
    intro: ["Madrid lever sent og belønner dere som tar helgen i rolig spansk tempo. Kunst, tapas, parker, fotball og nabolag med tydelig personlighet gjør byen ideell for en sosial langhelg.", "Madrid runs late and rewards travellers who follow its relaxed Spanish rhythm. Art, tapas, parks, football and distinctive neighbourhoods make it ideal for a social long weekend."],
    bestFor: [["Mat og tapas", "Food and tapas"], ["Fotball", "Football"], ["Kunst og kultur", "Art and culture"], ["Uteliv", "Nightlife"]],
    stay: ["3 netter", "3 nights"], areas: ["Centro, Malasaña og La Latina", "Centro, Malasaña and La Latina"], transport: ["Metro, buss og gange", "Metro, bus and walking"], airport: ["Adolfo Suárez Madrid–Barajas", "Adolfo Suárez Madrid–Barajas"],
    weekend: [["Fredag kveld", "Friday evening", "Tapas gjennom Centro", "Tapas through Centro", "Start ved Puerta del Sol og gå mot Plaza Mayor. Del småretter underveis og la kvelden fortsette i Huertas eller Malasaña.", "Begin at Puerta del Sol and walk towards Plaza Mayor. Share small plates along the way and continue in Huertas or Malasaña."], ["Lørdag", "Saturday", "Kunst, Retiro og sen middag", "Art, Retiro and a late dinner", "Velg ett museum i kunsttriangelet, gå gjennom Retiroparken og spar energi til en sen middag. Fotballinteresserte kan legge inn stadion eller kamp.", "Choose one museum in the Art Triangle, walk through Retiro Park and save energy for a late dinner. Football fans can add a stadium visit or match."], ["Søndag", "Sunday", "La Latina og markedsliv", "La Latina and market life", "Bruk formiddagen i La Latina. På søndager preger El Rastro gatene, før en lang lunsj gir en passende avslutning.", "Spend the morning in La Latina. On Sundays El Rastro fills the streets, followed by a long lunch for a fitting finish."]],
    districts: [["Centro", "Best for severdigheter, korte avstander og første besøk.", "Best for landmarks, short distances and a first visit."], ["Malasaña", "Kaféer, vintage, barer og kreativ storbystemning.", "Cafés, vintage shops, bars and creative city energy."], ["La Latina", "Tapas, historiske gater og søndagsmarked.", "Tapas, historic streets and the Sunday market."], ["Chueca", "Sentralt, livlig og fullt av restauranter og uteliv.", "Central, lively and filled with restaurants and nightlife."]],
    tips: [["Lev litt senere", "Shift your schedule later", "Middag og uteliv starter senere enn mange nordmenn er vant til.", "Dinner and nightlife begin later than many visitors expect."], ["Velg ett stort museum", "Choose one major museum", "Prado, Reina Sofía og Thyssen fortjener tid; ikke hast gjennom alle på én dag.", "The Prado, Reina Sofía and Thyssen deserve time; do not rush all three in one day."], ["Sjekk flyplasstillegget", "Check airport supplements", "Billettregler og tillegg varierer mellom metro, tog og ekspressbuss.", "Ticket rules and supplements differ between metro, rail and express bus."]],
    transportUrl: "https://www.crtm.es/", transportName: "CRTM"
  }),
  malaga: makeGuide({
    seo: ["Málaga-guide: sol, mat og sosial storbyferie", "Málaga guide: sun, food and a social city break"],
    intro: ["Málaga kombinerer strand og gamleby bedre enn de fleste helgebyer. Kunstmuseer, tapas, takterrasser og sjøluft gjør byen enkel å like året rundt.", "Málaga combines beach and Old Town better than most weekend cities. Art museums, tapas, rooftop terraces and sea air make it easy to enjoy throughout the year."],
    bestFor: [["Sol og strand", "Sun and beach"], ["Tapas", "Tapas"], ["Vennegjenger", "Groups of friends"], ["Kunst", "Art"]],
    stay: ["2–3 netter", "2–3 nights"], areas: ["Centro Histórico, Soho og La Malagueta", "Centro Histórico, Soho and La Malagueta"], transport: ["Gange, buss og lokaltog", "Walking, bus and local train"], airport: ["Málaga–Costa del Sol lufthavn", "Málaga–Costa del Sol Airport"],
    weekend: [["Fredag kveld", "Friday evening", "Tapas i gamlebyen", "Tapas in the Old Town", "Start rundt Calle Larios og gå videre mellom små torg. Del sjømat og tapas før en takterrasse gir utsikt over byen.", "Start around Calle Larios and move between small squares. Share seafood and tapas before taking in the city from a rooftop terrace."], ["Lørdag", "Saturday", "Alcazaba, kunst og strand", "Alcazaba, art and beach", "Besøk Alcazaba tidlig, velg ett kunstmuseum og gå mot havnen. Avslutt ettermiddagen på La Malagueta eller ved Muelle Uno.", "Visit the Alcazaba early, choose one art museum and walk towards the harbour. Finish at La Malagueta or Muelle Uno."], ["Søndag", "Sunday", "Marked og sjømat", "Market and seafood", "Se råvarene på Atarazanas-markedet når det er åpent, eller ta turen til Pedregalejo for strandpromenade og sjømat.", "See the produce at Atarazanas Market when open, or head to Pedregalejo for the seafront and seafood."]],
    districts: [["Centro Histórico", "Best for første besøk, tapas og kort vei til severdighetene.", "Best for a first visit, tapas and short walks to sights."], ["Soho", "Gatekunst, kultur og en litt mer moderne byfølelse.", "Street art, culture and a more contemporary city feel."], ["La Malagueta", "Nær strand, havn og gamlebyen.", "Close to the beach, harbour and Old Town."], ["Pedregalejo", "Roligere strandliv og sjømat litt utenfor sentrum.", "Slower beach life and seafood just outside the centre."]],
    tips: [["Besøk Alcazaba tidlig", "Visit the Alcazaba early", "Morgenen gir lavere temperatur og færre mennesker.", "Morning brings cooler temperatures and fewer visitors."], ["Bruk lokaltoget fra flyplassen", "Use the local train from the airport", "Cercanías er ofte den enkleste forbindelsen til sentrum.", "The Cercanías train is often the easiest connection to the centre."], ["Sjekk åpningstider", "Check opening hours", "Marked, museer og restauranter kan ha andre rytmer enn hjemme.", "Markets, museums and restaurants may follow different opening patterns." ]],
    transportUrl: "https://www.aena.es/en/malaga-costa-del-sol/getting-there/trains.html", transportName: "Aena"
  }),
  manchester: makeGuide({
    seo: ["Manchester-guide: fotball, musikk og pubkultur", "Manchester guide: football, music and pub culture"],
    intro: ["Manchester er en energisk helgeby med fotball, musikkhistorie, gode puber og en voksende matscene. Sentrum er kompakt, mens trikken gjør stadioner og nabolag enkle å nå.", "Manchester is an energetic weekend city built on football, music history, strong pubs and a growing food scene. The centre is compact, while trams make stadiums and neighbourhoods easy to reach."],
    bestFor: [["Fotball", "Football"], ["Musikk", "Music"], ["Pub og uteliv", "Pubs and nightlife"], ["Vennegjenger", "Groups of friends"]],
    stay: ["2–3 netter", "2–3 nights"], areas: ["Northern Quarter, Ancoats og Deansgate", "Northern Quarter, Ancoats and Deansgate"], transport: ["Metrolink, buss og gange", "Metrolink, bus and walking"], airport: ["Manchester lufthavn", "Manchester Airport"],
    weekend: [["Fredag kveld", "Friday evening", "Northern Quarter først", "Start in the Northern Quarter", "Finn middag, platebutikker og puber mellom de fargerike gatene. Fortsett mot Ancoats eller livemusikk i sentrum.", "Find dinner, record shops and pubs among the colourful streets. Continue towards Ancoats or live music in the centre."], ["Lørdag", "Saturday", "Fotball eller industrihistorie", "Football or industrial history", "Legg inn kamp eller stadiontur hvis det er målet. Ellers passer museer, kanalene i Castlefield og ettermiddag rundt Deansgate.", "Add a match or stadium tour if that is the goal. Otherwise choose museums, Castlefield's canals and an afternoon around Deansgate."], ["Søndag", "Sunday", "Brunsj og roligere bydeler", "Brunch and slower neighbourhoods", "Spis brunsj i Ancoats, gå langs kanalene eller ta trikken til Salford Quays før hjemreisen.", "Have brunch in Ancoats, walk the canals or take the tram to Salford Quays before heading home."]],
    districts: [["Northern Quarter", "Kreativt sentrum for barer, musikk, butikker og kaféer.", "A creative centre for bars, music, shops and cafés."], ["Ancoats", "Restauranter, bakerier og moderne byutvikling.", "Restaurants, bakeries and modern urban regeneration."], ["Deansgate", "Sentralt og praktisk for uteliv, shopping og transport.", "Central and practical for nightlife, shopping and transport."], ["Castlefield", "Kanaler, industrihistorie og roligere kveldsstemning.", "Canals, industrial history and a calmer evening atmosphere."]],
    tips: [["Kampbilletter krever planlegging", "Match tickets require planning", "Kjøp gjennom offisielle klubbsider eller godkjente aktører.", "Buy through official club sites or authorised sellers."], ["Bruk kontaktløs betaling riktig", "Use contactless payment correctly", "Følg Bee Networks regler for innsjekk og utsjekk på trikken.", "Follow Bee Network rules for touching in and out on trams."], ["Pakk for skiftende vær", "Pack for changing weather", "En lett regnjakke er nyttig selv når prognosen ser grei ut.", "A light rain jacket is useful even when the forecast looks fine."]],
    transportUrl: "https://tfgm.com/", transportName: "Bee Network"
  }),
  katowice: makeGuide({
    seo: ["Katowice-guide: Polens undervurderte helgeby", "Katowice guide: Poland’s underrated city break"],
    intro: ["Katowice har gått fra industriby til en overraskende kultur- og musikkdestinasjon. Moderne arkitektur, rimelig mat og korte avstander gjør byen til en annerledes polsk helg.", "Katowice has evolved from an industrial city into a surprising culture and music destination. Modern architecture, affordable food and short distances make it a different kind of Polish weekend."],
    bestFor: [["Skjulte perler", "Hidden gems"], ["Musikk og kultur", "Music and culture"], ["Industrihistorie", "Industrial history"], ["God verdi", "Great value"]],
    stay: ["2 netter", "2 nights"], areas: ["Śródmieście, Kultursonen og Nikiszowiec", "Śródmieście, Culture Zone and Nikiszowiec"], transport: ["Trikk, buss og tog", "Tram, bus and train"], airport: ["Katowice lufthavn", "Katowice Airport"],
    weekend: [["Fredag kveld", "Friday evening", "Bli kjent med sentrum", "Meet the city centre", "Start ved Rynek og Mariacka, der restauranter og barer gir en enkel inngang til byen.", "Start at Rynek and Mariacka, where restaurants and bars provide an easy introduction to the city."], ["Lørdag", "Saturday", "Kultursonen og gruvehistorien", "Culture Zone and mining history", "Se Spodek utenfra og velg mellom Schlesisk museum og konserter i Kultursonen. Senere kan dere utforske moderne matsteder i sentrum.", "See Spodek and choose between the Silesian Museum and events in the Culture Zone. Later explore the city's modern food scene."], ["Søndag", "Sunday", "Mursteinsbyen Nikiszowiec", "The brick district of Nikiszowiec", "Ta turen til Nikiszowiec for særegen arkitektur, kafé og en roligere avslutning før flyplassen.", "Head to Nikiszowiec for distinctive architecture, a café stop and a slower finish before the airport."]],
    districts: [["Śródmieście", "Praktisk sentrum med restauranter, barer og transport.", "A practical centre with restaurants, bars and transport."], ["Kultursonen", "Best for museer, konserter og moderne arkitektur.", "Best for museums, concerts and modern architecture."], ["Nikiszowiec", "Historisk arbeiderområde med rød murstein og egen karakter.", "A historic workers' district with red brick and unique character."], ["Ligota", "Grønnere og roligere med en mer lokal atmosfære.", "Greener and quieter with a more local atmosphere."]],
    tips: [["Kombiner med nabobyer", "Combine with nearby cities", "Det regionale nettverket gjør det mulig å besøke flere steder i Schlesien.", "The regional network makes it possible to visit more of Silesia."], ["Sjekk arrangementskalenderen", "Check the events calendar", "Konserter og festivaler kan være den beste grunnen til å velge helg.", "Concerts and festivals can be the best reason to choose a particular weekend."], ["Planlegg flyplasstransport", "Plan airport transport", "Flyplassen ligger et stykke utenfor byen; kontroller avgangstidene på forhånd.", "The airport is outside the city; check departure times in advance."]],
    transportUrl: "https://www.transportgzm.pl/", transportName: "Transport GZM"
  }),
  amsterdam: makeGuide({
    seo: ["Amsterdam-guide: kanaler, kultur og livlig weekend", "Amsterdam guide: canals, culture and a lively weekend"],
    intro: ["Amsterdam er kompakt, vakker og full av kontraster mellom kanalhus, verdensmuseer og kreative nabolag. Byen fungerer best når dere bestiller høydepunktene og lar resten oppstå til fots.", "Amsterdam is compact, beautiful and full of contrasts between canal houses, world-class museums and creative neighbourhoods. It works best when you book the highlights and discover the rest on foot."],
    bestFor: [["Kunst og museer", "Art and museums"], ["Vennegjenger", "Groups of friends"], ["Romantisk helg", "Romantic breaks"], ["Byvandring", "City walks"]],
    stay: ["2–3 netter", "2–3 nights"], areas: ["Jordaan, De Pijp og Centrum", "Jordaan, De Pijp and Centrum"], transport: ["Trikk, metro, ferge og gange", "Tram, metro, ferry and walking"], airport: ["Amsterdam Schiphol", "Amsterdam Schiphol"],
    weekend: [["Fredag kveld", "Friday evening", "Kanaler og Jordaan", "Canals and Jordaan", "Start med en rolig kanalrunde til fots og finn middag i Jordaan. De små gatene gir en bedre første kveld enn å jage mellom severdigheter.", "Begin with a relaxed canal walk and dinner in Jordaan. Its smaller streets make a better first evening than rushing between sights."], ["Lørdag", "Saturday", "Museum og nye bydeler", "Museums and new districts", "Bruk morgenen på ett forhåndsbestilt museum. Fortsett gjennom De Pijp, eller ta gratisfergen til Amsterdam Noord for en annen side av byen.", "Spend the morning at one pre-booked museum. Continue through De Pijp, or take the free ferry to Amsterdam Noord for another side of the city."], ["Søndag", "Sunday", "Marked, park og langsom avslutning", "Market, park and a slower finish", "Velg marked når det er åpent, en tur i Vondelpark eller kaféer i Oud-West før toget tilbake til Schiphol.", "Choose a market when open, a walk in Vondelpark or cafés in Oud-West before the train back to Schiphol."]],
    districts: [["Jordaan", "Kanalstemning, små restauranter og klassisk Amsterdam.", "Canal atmosphere, small restaurants and classic Amsterdam."], ["De Pijp", "Mat, marked og et livlig lokalt nabolag.", "Food, a market and a lively local neighbourhood."], ["Oud-West", "Kaféer, butikker og kort vei til Vondelpark.", "Cafés, shops and easy access to Vondelpark."], ["Amsterdam Noord", "Kreative områder og utsikt tilbake mot sentrum.", "Creative spaces and views back towards the centre."]],
    tips: [["Bestill museer tidlig", "Book museums early", "De mest populære inngangstidene kan forsvinne lenge før helgen.", "The most popular entry times can sell out well before your visit."], ["Respekter sykkelfeltene", "Respect cycle lanes", "Se begge veier og ikke stopp i de røde sykkelfeltene.", "Look both ways and never stop in the red cycle lanes."], ["Bruk kontaktløs transport", "Use contactless transport", "Sjekk alltid inn og ut med samme kort eller enhet.", "Always check in and out with the same card or device."]],
    transportUrl: "https://www.gvb.nl/en", transportName: "GVB"
  }),
  nice: makeGuide({
    seo: ["Nice-guide: Riviera, gamleby og strandliv", "Nice guide: Riviera, Old Town and beach life"],
    intro: ["Nice gir dere fransk storbyfølelse rett ved Middelhavet. Gamlebyen, markedene, kunsten og toget langs Rivieraen gjør byen til både reisemål og perfekt base.", "Nice offers French city life beside the Mediterranean. Its Old Town, markets, art and coastal trains make it both a destination and an excellent Riviera base."],
    bestFor: [["Sol og sjø", "Sun and sea"], ["Mat og marked", "Food and markets"], ["Kunst", "Art"], ["Utflukter", "Day trips"]],
    stay: ["3 netter", "3 nights"], areas: ["Vieux Nice, Carré d’Or og Port", "Vieux Nice, Carré d’Or and Port"], transport: ["Trikk, buss, tog og gange", "Tram, bus, train and walking"], airport: ["Nice Côte d’Azur", "Nice Côte d’Azur"],
    weekend: [["Fredag kveld", "Friday evening", "Gamlebyen og havet", "Old Town and the sea", "Gå gjennom Vieux Nice, finn middag i de smale gatene og avslutt langs Promenade des Anglais.", "Walk through Vieux Nice, find dinner in its narrow streets and finish along the Promenade des Anglais."], ["Lørdag", "Saturday", "Marked, utsikt og havn", "Market, views and harbour", "Start ved Cours Saleya, gå opp til Colline du Château og fortsett mot havnen. Sett av tid til strand eller museum etter interesse.", "Start at Cours Saleya, climb Castle Hill and continue towards the harbour. Leave time for the beach or a museum."], ["Søndag", "Sunday", "Rivieraen med tog", "The Riviera by train", "Ta en kort togtur til Villefranche-sur-Mer, Antibes eller Monaco, eller behold dagen rolig i Nice.", "Take a short train trip to Villefranche-sur-Mer, Antibes or Monaco, or keep the day relaxed in Nice."]],
    districts: [["Vieux Nice", "Historiske gater, marked, restauranter og kveldsstemning.", "Historic streets, market, restaurants and evening atmosphere."], ["Carré d’Or", "Sentralt mellom shopping, strand og transport.", "Central between shopping, beach and transport."], ["Port", "Restauranter, barer og en mer lokal havnefølelse.", "Restaurants, bars and a more local harbour atmosphere."], ["Libération", "Marked og hverdagsliv litt unna turistgatene.", "Market life and local atmosphere beyond the tourist streets."]],
    tips: [["Stranden består av stein", "The beach is pebbled", "Badesko og et tykkere underlag gjør stranddagen bedre.", "Water shoes and a padded mat make the beach more comfortable."], ["Bruk toget langs kysten", "Use the coastal train", "Mange Riviera-steder er enklere med tog enn leiebil.", "Many Riviera destinations are easier by train than by rental car."], ["Sjekk markedsdagene", "Check market days", "Cours Saleya skifter innhold gjennom uken.", "Cours Saleya changes character across the week."]],
    transportUrl: "https://www.lignesdazur.com/en", transportName: "Lignes d’Azur"
  }),
  milan: makeGuide({
    seo: ["Milano-guide: mote, mat og fotball", "Milan guide: fashion, food and football"],
    intro: ["Milano er mer enn shopping og domkirken. Aperitivo, design, fotball og nabolag med forskjellig rytme gjør byen til en stilfull og sosial weekend.", "Milan is more than shopping and the cathedral. Aperitivo, design, football and neighbourhoods with different rhythms create a stylish and social weekend."],
    bestFor: [["Mat og aperitivo", "Food and aperitivo"], ["Mote og design", "Fashion and design"], ["Fotball", "Football"], ["Kunst", "Art"]],
    stay: ["2–3 netter", "2–3 nights"], areas: ["Brera, Navigli og Centro", "Brera, Navigli and Centro"], transport: ["Metro, trikk og gange", "Metro, tram and walking"], airport: ["Malpensa, Linate eller Bergamo", "Malpensa, Linate or Bergamo"],
    weekend: [["Fredag kveld", "Friday evening", "Aperitivo i Navigli", "Aperitivo in Navigli", "Sjekk inn og gå langs kanalene. Velg aperitivo med omtanke og fortsett til middag eller barer i området.", "Check in and walk along the canals. Choose aperitivo carefully, then continue to dinner or bars nearby."], ["Lørdag", "Saturday", "Duomo, Brera og kveldskamp", "Duomo, Brera and an evening match", "Besøk Duomo tidlig, gå gjennom Galleria Vittorio Emanuele II og bruk ettermiddagen i Brera. Legg inn San Siro hvis kamp eller stadion står på planen.", "Visit the Duomo early, walk through Galleria Vittorio Emanuele II and spend the afternoon in Brera. Add San Siro for a match or stadium visit."], ["Søndag", "Sunday", "Design, parker og roligere gater", "Design, parks and slower streets", "Velg Porta Venezia, Fondazione Prada eller en rolig tur gjennom Parco Sempione før avreise.", "Choose Porta Venezia, Fondazione Prada or a relaxed walk through Parco Sempione before departure."]],
    districts: [["Brera", "Vakre gater, kunst, restauranter og sentral beliggenhet.", "Beautiful streets, art, restaurants and a central location."], ["Navigli", "Kanaler, aperitivo og livlige kvelder.", "Canals, aperitivo and lively evenings."], ["Porta Venezia", "Shopping, barer og en mangfoldig lokal scene.", "Shopping, bars and a diverse local scene."], ["Isola", "Moderne arkitektur, restauranter og kreativ atmosfære.", "Modern architecture, restaurants and a creative atmosphere." ]],
    tips: [["Bestill Duomo-taket", "Book the Duomo rooftop", "Velg tidspunkt på forhånd, særlig i helger.", "Choose a time in advance, especially at weekends."], ["Kontroller riktig flyplass", "Check the correct airport", "Milano betjenes av tre flyplasser med svært ulike reisetider.", "Milan is served by three airports with very different journey times."], ["Kontroller billetten", "Validate your journey", "Følg ATMs regler for billett eller kontaktløs betaling.", "Follow ATM rules for tickets or contactless payment."]],
    transportUrl: "https://www.atm.it/en/", transportName: "ATM Milano"
  }),
  helsinki: makeGuide({
    seo: ["Helsinki-guide: nordisk design og sjøliv", "Helsinki guide: Nordic design and seaside life"],
    intro: ["Helsinki er en avslappet hovedstad med design, badstuer, øyer og god mat innenfor korte avstander. Den passer for en enkel og innholdsrik helg med både byliv og frisk sjøluft.", "Helsinki is a relaxed capital of design, saunas, islands and good food within short distances. It suits an easy weekend combining city life and fresh sea air."],
    bestFor: [["Design", "Design"], ["Badstue", "Sauna"], ["Mat og marked", "Food and markets"], ["Rolig helg", "Relaxed weekends"]],
    stay: ["2–3 netter", "2–3 nights"], areas: ["Kluuvi, Punavuori og Katajanokka", "Kluuvi, Punavuori and Katajanokka"], transport: ["Trikk, metro, ferge og tog", "Tram, metro, ferry and train"], airport: ["Helsinki lufthavn", "Helsinki Airport"],
    weekend: [["Fredag kveld", "Friday evening", "Design District og middag", "Design District and dinner", "Start i Punavuori, gå mellom designbutikker og kaféer og avslutt med nordisk middag eller badstue.", "Begin in Punavuori, browse design shops and cafés, then finish with Nordic food or a sauna."], ["Lørdag", "Saturday", "Marked, kirker og Suomenlinna", "Market, churches and Suomenlinna", "Se havnen og Salutorget før fergen til Suomenlinna. Tilbake i sentrum kan dere velge bibliotek, museum eller sauna.", "See the harbour and Market Square before taking the ferry to Suomenlinna. Back in the centre, choose a library, museum or sauna."], ["Søndag", "Sunday", "Kyst, kafé og en rolig avslutning", "Coast, café and a slow finish", "Gå rundt Töölö, se Sibeliusmonumentet eller finn en kafé ved sjøen før toget til flyplassen.", "Walk through Töölö, see the Sibelius Monument or find a seaside café before taking the train to the airport."]],
    districts: [["Kluuvi", "Mest praktisk for stasjonen, shopping og første besøk.", "Most practical for the station, shopping and a first visit."], ["Punavuori", "Design, restauranter og hyggelige bygater.", "Design, restaurants and pleasant city streets."], ["Katajanokka", "Jugendarkitektur, havn og roligere kvelder.", "Art Nouveau architecture, harbour and quieter evenings."], ["Kallio", "Barer, kaféer og en yngre lokal stemning.", "Bars, cafés and a younger local atmosphere." ]],
    tips: [["Ta med badetøy", "Bring swimwear", "Badstue er en naturlig del av Helsinki-opplevelsen.", "Sauna is a natural part of the Helsinki experience."], ["AB-billett til Suomenlinna", "AB ticket to Suomenlinna", "En HSL-billett som inkluderer sone A gjelder på fergen; AB er nok fra Salutorget.", "An HSL ticket that includes zone A is valid on the ferry; AB is sufficient from Market Square."], ["Kle dere lagvis", "Dress in layers", "Vind ved sjøen kan endre temperaturfølelsen raskt.", "Seaside wind can change how the temperature feels quickly."]],
    transportUrl: "https://www.hsl.fi/en", transportName: "HSL"
  }),
  copenhagen: makeGuide({
    seo: ["København-guide: mat, design og barliv", "Copenhagen guide: food, design and bars"],
    intro: ["København er lett å navigere og vanskelig å bli ferdig med. Havnebad, design, bakerier, restauranter og ulike nabolag gjør byen perfekt for en kort, sosial tur.", "Copenhagen is easy to navigate and difficult to finish exploring. Harbour baths, design, bakeries, restaurants and distinct neighbourhoods make it perfect for a short social trip."],
    bestFor: [["Mat og bakerier", "Food and bakeries"], ["Design", "Design"], ["Vennegjenger", "Groups of friends"], ["Kort storbyhelg", "Easy weekends"]],
    stay: ["2–3 netter", "2–3 nights"], areas: ["Indre By, Vesterbro og Nørrebro", "Indre By, Vesterbro and Nørrebro"], transport: ["Metro, buss, tog og sykkel", "Metro, bus, train and bicycle"], airport: ["Københavns lufthavn", "Copenhagen Airport"],
    weekend: [["Fredag kveld", "Friday evening", "Vesterbro og Kødbyen", "Vesterbro and the Meatpacking District", "Start med middag på Vesterbro og fortsett mellom barene i Kødbyen. Alt ligger nær stasjonen og er enkelt første kveld.", "Begin with dinner in Vesterbro and continue through the Meatpacking District's bars. It is close to the station and easy for a first night."], ["Lørdag", "Saturday", "Klassikere og kanaler", "Classics and canals", "Gå gjennom Indre By til Nyhavn, velg kanalbåt eller museum og fortsett til Christianshavn. Spar plass til et godt kveldsmåltid.", "Walk through the centre to Nyhavn, choose a canal tour or museum, then continue to Christianshavn. Save room for a strong dinner."], ["Søndag", "Sunday", "Nørrebro og bakerirunde", "Nørrebro and a bakery crawl", "Start med bakst og kaffe, gå gjennom Assistens Kirkegård og utforsk Jægersborggade før metroen til flyplassen.", "Start with pastry and coffee, walk through Assistens Cemetery and explore Jægersborggade before taking the metro to the airport."]],
    districts: [["Indre By", "Best for klassiske severdigheter og første besøk.", "Best for classic sights and a first visit."], ["Vesterbro", "Restauranter, barer og kort vei fra sentralstasjonen.", "Restaurants, bars and easy access from Central Station."], ["Nørrebro", "Mangfoldig mat, småbutikker og lokal stemning.", "Diverse food, independent shops and local atmosphere."], ["Christianshavn", "Kanaler, arkitektur og roligere morgener.", "Canals, architecture and quieter mornings." ]],
    tips: [["Reserver populære restauranter", "Reserve popular restaurants", "De mest omtalte stedene fylles tidlig i helgene.", "The most talked-about places fill early at weekends."], ["Sykkel krever oppmerksomhet", "Cycling requires attention", "Følg lokale regler og signaler hvis dere leier sykkel.", "Follow local rules and signals if renting bikes."], ["Metro til flyplassen", "Metro to the airport", "Forbindelsen er rask, men kontroller sone og billett før avreise.", "The connection is fast, but check your zone and ticket before travelling."]],
    transportUrl: "https://dinoffentligetransport.dk/en/", transportName: "DOT"
  }),
  skopje: makeGuide({
    seo: ["Skopje-guide: rimelig og særegen storbyhelg", "Skopje guide: an affordable and distinctive city break"],
    intro: ["Skopje er kontrastfylt, rimelig og full av historier. Den gamle basaren, brutalistisk arkitektur, lokale retter og fjellene rett utenfor byen gjør helgen uvanlig variert.", "Skopje is full of contrasts, affordable and rich in stories. The Old Bazaar, brutalist architecture, local food and mountains just outside the city create an unusually varied weekend."],
    bestFor: [["Skjulte perler", "Hidden gems"], ["God verdi", "Great value"], ["Historie", "History"], ["Naturutflukt", "Nature trips"]],
    stay: ["2–3 netter", "2–3 nights"], areas: ["Centar, den gamle basaren og Debar Maalo", "Centar, Old Bazaar and Debar Maalo"], transport: ["Buss, taxi og gange", "Bus, taxi and walking"], airport: ["Skopje internasjonale lufthavn", "Skopje International Airport"],
    weekend: [["Fredag kveld", "Friday evening", "Sentrum og Debar Maalo", "Centre and Debar Maalo", "Se kontrastene rundt Makedonia-plassen og finn deretter middag i Debar Maalo, kjent for restauranter og kafana-stemning.", "See the contrasts around Macedonia Square, then find dinner in Debar Maalo, known for restaurants and kafana atmosphere."], ["Lørdag", "Saturday", "Basaren og Kale", "Bazaar and Kale", "Kryss Steinbroen, bruk god tid i den gamle basaren og gå opp mot Kale-festningen. Velg museum eller byens modernistiske arkitektur senere.", "Cross Stone Bridge, take time in the Old Bazaar and walk towards Kale Fortress. Choose a museum or modernist architecture later."], ["Søndag", "Sunday", "Matka Canyon", "Matka Canyon", "Sett av flere timer til Matka Canyon hvis været passer. Avtal transport og returreise på forhånd.", "Set aside several hours for Matka Canyon when weather allows. Arrange transport and the return journey in advance."]],
    districts: [["Centar", "Praktisk for severdigheter og første besøk.", "Practical for sightseeing and a first visit."], ["Den gamle basaren", "Historie, håndverk, tehus og tradisjonell mat.", "History, crafts, tea houses and traditional food."], ["Debar Maalo", "Restauranter, barer og lokal kveldsstemning.", "Restaurants, bars and local evening atmosphere."], ["Vodno", "Roligere base nær natur og utsiktspunkter.", "A quieter base close to nature and viewpoints." ]],
    tips: [["Ha litt kontanter", "Carry some cash", "Kort fungerer mange steder, men mindre utsalg kan foretrekke kontanter.", "Cards work in many places, but smaller businesses may prefer cash."], ["Avtal taxi eller bruk app", "Agree taxi fares or use an app", "Bekreft pris og betalingsmåte før lengre turer.", "Confirm the fare and payment method before longer trips."], ["Planlegg Matka etter været", "Plan Matka around weather", "Vannstand, varme og regn påvirker opplevelsen.", "Water levels, heat and rain can affect the experience."]],
    transportUrl: "https://skopjebus.mk/en/", transportName: "JSP Skopje"
  }),
  "palma-de-mallorca": makeGuide({
    seo: ["Palma-guide: strand, gamleby og middelhavsmat", "Palma guide: beach, Old Town and Mediterranean food"],
    intro: ["Palma gir dere både ekte storbyhelg og tilgang til sjøen. Katedralen, gamlebyen, markedene og strandklubbene gjør byen til mer enn et stopp på vei videre på Mallorca.", "Palma offers both a genuine city break and easy access to the sea. Its cathedral, Old Town, markets and beach clubs make it much more than a gateway to Mallorca."],
    bestFor: [["Strand og by", "Beach and city"], ["Mat og vin", "Food and wine"], ["Vennegjenger", "Groups of friends"], ["Par", "Couples"]],
    stay: ["3 netter", "3 nights"], areas: ["Gamlebyen, Santa Catalina og Portixol", "Old Town, Santa Catalina and Portixol"], transport: ["Buss, gange og sykkel", "Bus, walking and bicycle"], airport: ["Palma de Mallorca lufthavn", "Palma de Mallorca Airport"],
    weekend: [["Fredag kveld", "Friday evening", "Santa Catalina til middag", "Dinner in Santa Catalina", "Start rundt markedet og sidegatene i Santa Catalina. Området gjør det enkelt å kombinere middag og barer.", "Begin around the market and side streets of Santa Catalina. The area makes it easy to combine dinner and bars."], ["Lørdag", "Saturday", "Katedral, gamleby og sjø", "Cathedral, Old Town and sea", "Besøk La Seu tidlig, gå gjennom de historiske gatene og fortsett langs havnen. Velg strand i nærheten eller en lang lunsj.", "Visit La Seu early, walk the historic streets and continue along the harbour. Choose a nearby beach or a long lunch."], ["Søndag", "Sunday", "Portixol eller utflukt", "Portixol or an excursion", "Gå eller sykle mot Portixol for sjøfront og lunsj. Med mer tid kan en forhåndsplanlagt tur utenfor byen passe.", "Walk or cycle towards Portixol for the seafront and lunch. With more time, add a pre-planned trip beyond the city."]],
    districts: [["Gamlebyen", "Historie, shopping og kort vei til katedralen.", "History, shopping and easy access to the cathedral."], ["Santa Catalina", "Marked, restauranter, barer og sosial stemning.", "Market, restaurants, bars and social atmosphere."], ["Portixol", "Sjøfront, roligere morgener og strandfølelse.", "Seafront, quieter mornings and a beach atmosphere."], ["La Lonja", "Sentralt, vakkert og livlig om kvelden.", "Central, beautiful and lively in the evening." ]],
    tips: [["Skille mellom Palma og øya", "Separate Palma from the island", "Ikke legg inn for mange lange Mallorca-utflukter i en kort byhelg.", "Do not add too many long Mallorca excursions to a short city break."], ["Bestill billetter til katedralen", "Book the cathedral", "Sjekk åpningstider og billetter før dere går.", "Check opening hours and tickets before visiting."], ["Vær obs på sommervarmen", "Mind the summer heat", "Legg de lengste gåturene til morgen eller kveld.", "Plan longer walks for morning or evening."]],
    transportUrl: "https://www.emtpalma.cat/en/", transportName: "EMT Palma"
  }),
  gothenburg: makeGuide({
    seo: ["Gøteborg-guide: sjømat og sosial helg", "Gothenburg guide: seafood and a social weekend"],
    intro: ["Gøteborg er en lettvint helgeby med sjømat, trikker, parker og vennlige nabolag. Den korte reisen fra Norge gjør det enkelt å bruke tiden på mat, kultur og sosialt byliv.", "Gothenburg is an easy weekend city of seafood, trams, parks and welcoming neighbourhoods. Short travel times from Norway leave more time for food, culture and social city life."],
    bestFor: [["Kort storbytur", "Easy escapes"], ["Sjømat", "Seafood"], ["Vennegjenger", "Groups of friends"], ["Konserter og kultur", "Concerts and culture"]],
    stay: ["2 netter", "2 nights"], areas: ["Centrum, Haga og Linné", "Centrum, Haga and Linné"], transport: ["Trikk, buss, båt og gange", "Tram, bus, ferry and walking"], airport: ["Göteborg Landvetter lufthavn", "Gothenburg Landvetter Airport"],
    weekend: [["Fredag kveld", "Friday evening", "Linné og første middag", "Linné and the first dinner", "Start rundt Linnégatan med middag og barer. Avstandene er korte, og stemningen passer en uanstrengt første kveld.", "Begin around Linnégatan with dinner and bars. Distances are short and the atmosphere suits an easy first evening."], ["Lørdag", "Saturday", "Marked, Haga og havn", "Market, Haga and harbour", "Se Feskekörka-området, gå gjennom Haga og velg museum, shopping eller en båttur. Avslutt med sjømat eller konsert.", "See the Feskekörka area, walk through Haga and choose a museum, shopping or a boat trip. Finish with seafood or a concert."], ["Søndag", "Sunday", "Skjærgård eller park", "Archipelago or park", "Med god tid kan kollektivbåten gi en smak av skjærgården. Ellers passer Slottsskogen og en rolig brunsj.", "With enough time, a public ferry offers a taste of the archipelago. Otherwise choose Slottsskogen and a relaxed brunch."]],
    districts: [["Centrum", "Best for shopping, transport og førstegangsbesøk.", "Best for shopping, transport and a first visit."], ["Haga", "Historiske trehus, kaféer og rolig dagstemning.", "Historic wooden houses, cafés and a calm daytime atmosphere."], ["Linné", "Restauranter, puber og kort vei til Slottsskogen.", "Restaurants, pubs and easy access to Slottsskogen."], ["Majorna", "Mer lokal stemning, musikk og hyggelige gater.", "A more local atmosphere, music and pleasant streets." ]],
    tips: [["Samme billett til skjærgården", "Use the same ticket to the archipelago", "Båtene til den sørlige skjærgården inngår i sone A, og samme Västtrafik-billett gjelder fra byen.", "Ferries to the southern archipelago are included in zone A, and the same Västtrafik ticket is valid from the city."], ["Sjekk konsertkalenderen", "Check the concert calendar", "Arrangementer kan avgjøre både hotellpris og den beste helgen.", "Events can affect both hotel prices and the best weekend to visit."], ["Reserver bord på populære sjømatrestauranter", "Book popular seafood restaurants", "De mest kjente stedene fylles raskt fredag og lørdag.", "Well-known places fill quickly on Friday and Saturday."]],
    transportUrl: "https://www.vasttrafik.se/en/", transportName: "Västtrafik"
  })
};

export const allDestinationGuides = guides;
