import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { DiscoverCarsCta } from "@/components/discovercars-cta";

type PageProps = { params: Promise<{ lang: string }> };

const costs = [
  ["01", "Bagasje og setevalg", "Baggage and seat selection", "En lav flypris kan mangle håndbagasje, innsjekket bagasje eller setevalg. Sammenlign billettens sluttpris for alle som skal reise.", "A low fare may exclude cabin baggage, checked baggage or seat selection. Compare the final ticket cost for everyone travelling."],
  ["02", "Transport til og fra flyplassen", "Transport to and from the airport", "Ta med reisen til avreiseflyplassen og videre fra ankomstflyplassen. En fjern flyplass kan gjøre den billigste flybilletten dyrere totalt.", "Include travel to the departure airport and onward travel after landing. A distant airport can make the cheapest fare more expensive overall."],
  ["03", "Hotellskatter og tillegg", "Hotel taxes and extras", "Kontroller om lokale skatter, frokost, parkering eller andre gebyrer kommer i tillegg. Sammenlign beløpet for hele oppholdet.", "Check whether local taxes, breakfast, parking or other fees are added. Compare the amount for the complete stay."],
  ["04", "Betaling og valuta", "Payment and currency", "Se hvilken valuta du betaler i, og om kortutsteder eller minibank kan legge til vekslingskostnader. Velg betalingsmåte etter vilkårene som faktisk gjelder.", "Check the payment currency and whether your card provider or cash machine may add conversion costs. Choose a payment method based on the actual conditions."],
  ["05", "Mobildata og tilkobling", "Mobile data and connectivity", "Kontroller hva mobilabonnementet dekker på reisemålet. Dersom du trenger ekstra data, bør kostnaden være med i budsjettet før avreise.", "Check what your mobile plan covers at the destination. If you need additional data, include the cost in the budget before departure."],
  ["06", "Leiebilens reelle sluttpris", "The true rental car cost", "Se etter forsikring, depositum, drivstoffvilkår, bom, parkering og eventuelle grenser for kjørelengde. Ikke vurder bare døgnprisen.", "Check insurance, deposits, fuel terms, tolls, parking and any mileage limits. Do not judge the offer by the daily rate alone."],
  ["07", "Billetter og reservasjoner", "Tickets and reservations", "Aktiviteter kan koste mer ved inngangen eller bli utsolgt. Kontroller pris, bestillingsgebyr og avbestillingsvilkår før du legger dem i planen.", "Activities may cost more at the entrance or sell out. Check the price, booking fee and cancellation conditions before adding them to the plan."],
  ["08", "Småkjøp gjennom dagen", "Small purchases during the day", "Kaffe, vann, snacks, kollektivbilletter og bagasjeoppbevaring kan bli en merkbar sum. Legg inn en enkel dagsramme og en liten buffer.", "Coffee, water, snacks, public transport and luggage storage can add up. Set a simple daily allowance and a small contingency."],
];

const faq = [
  ["Hva er den vanligste glemte reisekostnaden?", "What is the most commonly missed travel cost?", "Det varierer, men bagasje, flyplasstransport, hotelltillegg og lokal transport er kostnader mange undervurderer når de ser den første prisen.", "It varies, but baggage, airport transfers, hotel extras and local transport are often underestimated when people see the initial price."],
  ["Hvordan sammenligner jeg to weekendturer?", "How do I compare two weekend trips?", "Lag én totalsum per person med fly, bagasje, overnatting, transport, mat, aktiviteter og buffer. Sammenlign deretter turene på samme grunnlag.", "Create one total per person covering flights, baggage, accommodation, transport, food, activities and contingency. Then compare the trips on the same basis."],
  ["Hvorfor trenger jeg en buffer?", "Why do I need a contingency?", "En buffer dekker uventet transport, prisendringer eller småkjøp uten at resten av budsjettet sprekker. Den trenger ikke brukes opp.", "A contingency covers unexpected transport, price changes or small purchases without disrupting the rest of the budget. It does not need to be spent."],
];

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { lang } = await params;
  const no = lang === "no";
  return {
    title: no ? "Skjulte kostnader på weekendtur – dette bør du sjekke | Flyferie.no" : "Hidden weekend trip costs – what to check | Flyferie.no",
    description: no ? "Unngå budsjettsprekk ved å kontrollere bagasje, flyplasstransport, hotelltillegg, valuta, mobildata og leiebil." : "Avoid budget surprises by checking baggage, airport transfers, hotel extras, currency, mobile data and car rental costs.",
    alternates: { canonical: `/${lang}/guides/hidden-travel-costs`, languages: { "nb-NO": "/no/guides/hidden-travel-costs", en: "/en/guides/hidden-travel-costs", "x-default": "/no/guides/hidden-travel-costs" } },
  };
}

export default async function HiddenTravelCostsPage({ params }: PageProps) {
  const { lang } = await params;
  if (lang !== "no" && lang !== "en") notFound();
  const no = lang === "no";
  const other = no ? "en" : "no";
  const pageUrl = `https://flyferie.no/${lang}/guides/hidden-travel-costs`;
  const jsonLd = { "@context": "https://schema.org", "@graph": [
    { "@type": "Article", headline: no ? "Skjulte kostnader på weekendtur" : "Hidden weekend trip costs", description: no ? "En praktisk oversikt over reisekostnadene som ofte glemmes." : "A practical overview of travel costs that are often overlooked.", inLanguage: no ? "nb-NO" : "en", url: pageUrl, publisher: { "@id": "https://flyferie.no/#organization" } },
    { "@type": "FAQPage", mainEntity: faq.map((item) => ({ "@type": "Question", name: no ? item[0] : item[1], acceptedAnswer: { "@type": "Answer", text: no ? item[2] : item[3] } })) },
    { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: no ? "Forside" : "Home", item: `https://flyferie.no/${lang}` }, { "@type": "ListItem", position: 2, name: no ? "Guider" : "Guides", item: `https://flyferie.no/${lang}/guides` }, { "@type": "ListItem", position: 3, name: no ? "Skjulte reisekostnader" : "Hidden travel costs", item: pageUrl }] },
  ] };

  return <main className="min-h-screen bg-[#fffaf1] text-[#17332f]">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} />
    <header className="bg-[#102f2b] text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><Link href={`/${lang}`}><Image src="/flyferie-logo-v9.png" alt="Flyferie.no" width={480} height={200} priority className="h-auto w-[185px] sm:w-[225px]" /></Link><div className="flex items-center gap-4"><Link href={`/${lang}/guides/weekend-trip-budget`} className="text-sm font-bold">{no ? "Budsjettguide" : "Budget guide"}</Link><Link href={`/${other}/guides/hidden-travel-costs`} className="rounded-full border border-white/40 px-4 py-2 text-sm font-bold">{no ? "EN" : "NO"}</Link></div></div></header>
    <section className="relative overflow-hidden bg-[#173f39] px-5 py-16 text-white sm:py-24 lg:px-8"><div className="absolute -right-24 -top-28 h-80 w-80 rounded-full bg-[#f4b860]/25 blur-3xl" /><div className="relative mx-auto max-w-6xl"><Link href={`/${lang}/guides`} className="text-sm font-bold text-[#ffd078]">← {no ? "Tilbake til guidene" : "Back to the guides"}</Link><p className="mt-9 text-xs font-bold uppercase tracking-[.22em] text-[#ffd078]">{no ? "Se hele reisekostnaden" : "See the complete travel cost"}</p><h1 className="display mt-3 max-w-5xl text-[48px] font-bold leading-[.98] sm:text-7xl lg:text-[82px]">{no ? "Skjulte kostnader på weekendtur" : "Hidden costs on a weekend trip"}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/80 sm:text-xl">{no ? "Den første prisen viser sjelden hele turen. Med noen enkle kontroller kan du oppdage tilleggene før de blir en overraskelse." : "The first price rarely shows the complete trip. A few simple checks can reveal the extras before they become a surprise."}</p></div></section>
    <section className="px-5 py-12 sm:py-16 lg:px-8"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#e16f59]">{no ? "Kontroller før du bestiller" : "Check before booking"}</p><h2 className="display mt-3 max-w-4xl text-[38px] font-bold leading-tight sm:text-5xl">{no ? "Åtte kostnader som lett blir oversett" : "Eight costs that are easy to overlook"}</h2><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{costs.map((item) => <article key={item[0]} className="rounded-[26px] border border-[#17332f]/10 bg-white p-6 shadow-sm"><span className="rounded-full bg-[#f4d7a1] px-3 py-1.5 text-xs font-bold text-[#b94f3d]">{item[0]}</span><h3 className="display mt-5 text-2xl font-bold leading-tight">{no ? item[1] : item[2]}</h3><p className="mt-3 leading-7 text-[#48645f]">{no ? item[3] : item[4]}</p></article>)}</div><div className="mt-8"><DiscoverCarsCta lang={lang} variant="compact" showGuideLink /></div></div></section>
    <section className="bg-[#edf4ef] px-5 py-12 lg:px-8 lg:py-16"><div className="mx-auto grid max-w-6xl gap-7 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#1e776e]">{no ? "En bedre sammenligning" : "A better comparison"}</p><h2 className="display mt-3 text-[38px] font-bold leading-tight sm:text-5xl">{no ? "Regn ut pris per person" : "Calculate the cost per person"}</h2></div><div className="rounded-[24px] bg-white p-7 shadow-sm sm:p-9"><p className="text-lg leading-8 text-[#365b55]">{no ? "Legg sammen fly, bagasje, overnatting, transport, mat, aktiviteter og buffer. Del totalsummen på antall reisende. Da blir det enklere å sammenligne to reisemål eller ulike reisedatoer på samme grunnlag." : "Add flights, baggage, accommodation, transport, food, activities and contingency. Divide the total by the number of travellers. This makes it easier to compare destinations or travel dates on the same basis."}</p></div></div></section>
    <section className="px-5 py-12 sm:py-16 lg:px-8"><div className="mx-auto max-w-4xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#e16f59]">{no ? "Vanlige spørsmål" : "Frequently asked questions"}</p><div className="mt-7 space-y-4">{faq.map((item) => <article key={item[1]} className="rounded-[22px] border border-[#17332f]/10 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">{no ? item[0] : item[1]}</h2><p className="mt-3 leading-7 text-[#48645f]">{no ? item[2] : item[3]}</p></article>)}</div><div className="mt-8 flex flex-wrap gap-3"><Link href={`/${lang}/guides/weekend-trip-budget`} className="inline-flex rounded-full bg-[#17332f] px-6 py-3.5 font-bold text-white">{no ? "Lag budsjett for turen" : "Build a trip budget"} →</Link><Link href={`/${lang}/guides/cheap-flights`} className="inline-flex rounded-full border border-[#17332f]/25 bg-white px-6 py-3.5 font-bold">{no ? "Sammenlign flypriser" : "Compare flight prices"} →</Link></div></div></section>
    <footer className="bg-[#102f2b] px-5 py-10 text-white/65"><div className="mx-auto flex max-w-7xl flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><Image src="/flyferie-logo-v9.png" alt="Flyferie.no" width={480} height={200} className="h-auto w-[210px]" /><p className="text-sm">© 2026 Flyferie.no · {no ? "Reiseinspirasjon for nye opplevelser" : "Travel inspiration for new experiences"}</p></div></footer>
  </main>;
}
